version: "3"
# container
services: 
  redis-server:
    image: "redis"
  node-app:
    # restart: always
    # restart: unless-stopped
    # restart: "no"
    restart: on-failure
    build: .
    ports:
      # client(3000):(5000)server
      - "4001:8081"
